/**
 * This class is generated by jOOQ
 */
package com.bridge.survey.entity.tables;


import com.bridge.survey.entity.Keys;
import com.bridge.survey.entity.Public;
import com.bridge.survey.entity.tables.records.SurveyDistributionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import java.sql.Time;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SurveyDistribution extends TableImpl<SurveyDistributionRecord> {

    private static final long serialVersionUID = 439401782;

    /**
     * The reference instance of <code>public.survey_distribution</code>
     */
    public static final SurveyDistribution SURVEY_DISTRIBUTION = new SurveyDistribution();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SurveyDistributionRecord> getRecordType() {
        return SurveyDistributionRecord.class;
    }

    /**
     * The column <code>public.survey_distribution.id</code>.
     */
    public final TableField<SurveyDistributionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.survey_distribution.survey_id</code>.
     */
    public final TableField<SurveyDistributionRecord, Long> SURVEY_ID = createField("survey_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.survey_distribution.name</code>.
     */
    public final TableField<SurveyDistributionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.survey_distribution.closes_at</code>.
     */
    public final TableField<SurveyDistributionRecord, Time> CLOSES_AT = createField("closes_at", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

    /**
     * The column <code>public.survey_distribution.created_at</code>.
     */
    public final TableField<SurveyDistributionRecord, Time> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>public.survey_distribution.updated_at</code>.
     */
    public final TableField<SurveyDistributionRecord, Time> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>public.survey_distribution.created_by</code>.
     */
    public final TableField<SurveyDistributionRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.survey_distribution.updated_by</code>.
     */
    public final TableField<SurveyDistributionRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.survey_distribution</code> table reference
     */
    public SurveyDistribution() {
        this("survey_distribution", null);
    }

    /**
     * Create an aliased <code>public.survey_distribution</code> table reference
     */
    public SurveyDistribution(String alias) {
        this(alias, SURVEY_DISTRIBUTION);
    }

    private SurveyDistribution(String alias, Table<SurveyDistributionRecord> aliased) {
        this(alias, aliased, null);
    }

    private SurveyDistribution(String alias, Table<SurveyDistributionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SurveyDistributionRecord> getPrimaryKey() {
        return Keys.SURVEY_DISTRIBUTION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SurveyDistributionRecord>> getKeys() {
        return Arrays.<UniqueKey<SurveyDistributionRecord>>asList(Keys.SURVEY_DISTRIBUTION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SurveyDistributionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SurveyDistributionRecord, ?>>asList(Keys.SURVEY_DISTRIBUTION__SURVEY_DISTRIBUTION_SURVEY_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyDistribution as(String alias) {
        return new SurveyDistribution(alias, this);
    }

    /**
     * Rename this table
     */
    public SurveyDistribution rename(String name) {
        return new SurveyDistribution(name, null);
    }
}
