/**
 * This class is generated by jOOQ
 */
package com.bridge.entity;


import com.bridge.entity.tables.AnswerOptions;
import com.bridge.entity.tables.AnswerTypes;
import com.bridge.entity.tables.SurveyDistributions;
import com.bridge.entity.tables.SurveyQuestions;
import com.bridge.entity.tables.SurveyTemplates;
import com.bridge.entity.tables.Surveys;
import com.bridge.entity.tables.records.AnswerOptionsRecord;
import com.bridge.entity.tables.records.AnswerTypesRecord;
import com.bridge.entity.tables.records.SurveyDistributionsRecord;
import com.bridge.entity.tables.records.SurveyQuestionsRecord;
import com.bridge.entity.tables.records.SurveyTemplatesRecord;
import com.bridge.entity.tables.records.SurveysRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AnswerOptionsRecord> QUESTION_OPTIONS_PKEY = UniqueKeys0.QUESTION_OPTIONS_PKEY;
    public static final UniqueKey<AnswerTypesRecord> ANSWER_TYPE_PKEY = UniqueKeys0.ANSWER_TYPE_PKEY;
    public static final UniqueKey<SurveyDistributionsRecord> SURVEY_DISTRIBUTION_PKEY = UniqueKeys0.SURVEY_DISTRIBUTION_PKEY;
    public static final UniqueKey<SurveyQuestionsRecord> SURVEY_QUESTION_PKEY = UniqueKeys0.SURVEY_QUESTION_PKEY;
    public static final UniqueKey<SurveyTemplatesRecord> SURVEY_TEMPLATE_PKEY = UniqueKeys0.SURVEY_TEMPLATE_PKEY;
    public static final UniqueKey<SurveysRecord> SURVEYS_PKEY = UniqueKeys0.SURVEYS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SurveyDistributionsRecord, SurveysRecord> SURVEY_DISTRIBUTIONS__SURVEY_DISTRIBUTION_SURVEY_ID_FKEY = ForeignKeys0.SURVEY_DISTRIBUTIONS__SURVEY_DISTRIBUTION_SURVEY_ID_FKEY;
    public static final ForeignKey<SurveyQuestionsRecord, SurveysRecord> SURVEY_QUESTIONS__SURVEYS_SURVEY_ID = ForeignKeys0.SURVEY_QUESTIONS__SURVEYS_SURVEY_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AnswerOptionsRecord> QUESTION_OPTIONS_PKEY = createUniqueKey(AnswerOptions.ANSWER_OPTIONS, "question_options_pkey", AnswerOptions.ANSWER_OPTIONS.ID);
        public static final UniqueKey<AnswerTypesRecord> ANSWER_TYPE_PKEY = createUniqueKey(AnswerTypes.ANSWER_TYPES, "answer_type_pkey", AnswerTypes.ANSWER_TYPES.ID);
        public static final UniqueKey<SurveyDistributionsRecord> SURVEY_DISTRIBUTION_PKEY = createUniqueKey(SurveyDistributions.SURVEY_DISTRIBUTIONS, "survey_distribution_pkey", SurveyDistributions.SURVEY_DISTRIBUTIONS.ID);
        public static final UniqueKey<SurveyQuestionsRecord> SURVEY_QUESTION_PKEY = createUniqueKey(SurveyQuestions.SURVEY_QUESTIONS, "survey_question_pkey", SurveyQuestions.SURVEY_QUESTIONS.ID);
        public static final UniqueKey<SurveyTemplatesRecord> SURVEY_TEMPLATE_PKEY = createUniqueKey(SurveyTemplates.SURVEY_TEMPLATES, "survey_template_pkey", SurveyTemplates.SURVEY_TEMPLATES.ID);
        public static final UniqueKey<SurveysRecord> SURVEYS_PKEY = createUniqueKey(Surveys.SURVEYS, "surveys_pkey", Surveys.SURVEYS.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<SurveyDistributionsRecord, SurveysRecord> SURVEY_DISTRIBUTIONS__SURVEY_DISTRIBUTION_SURVEY_ID_FKEY = createForeignKey(com.bridge.entity.Keys.SURVEYS_PKEY, SurveyDistributions.SURVEY_DISTRIBUTIONS, "survey_distributions__survey_distribution_survey_id_fkey", SurveyDistributions.SURVEY_DISTRIBUTIONS.SURVEY_ID);
        public static final ForeignKey<SurveyQuestionsRecord, SurveysRecord> SURVEY_QUESTIONS__SURVEYS_SURVEY_ID = createForeignKey(com.bridge.entity.Keys.SURVEYS_PKEY, SurveyQuestions.SURVEY_QUESTIONS, "survey_questions__surveys_survey_id", SurveyQuestions.SURVEY_QUESTIONS.SURVEY_ID);
    }
}
