/**
 * This class is generated by jOOQ
 */
package com.bridge.entity;


import com.bridge.entity.tables.AnswerOptions;
import com.bridge.entity.tables.AnswerTypes;
import com.bridge.entity.tables.SurveyDistributions;
import com.bridge.entity.tables.SurveyQuestions;
import com.bridge.entity.tables.SurveyTemplates;
import com.bridge.entity.tables.Surveys;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 127275455;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.answer_options</code>.
     */
    public final AnswerOptions ANSWER_OPTIONS = com.bridge.entity.tables.AnswerOptions.ANSWER_OPTIONS;

    /**
     * The table <code>public.answer_types</code>.
     */
    public final AnswerTypes ANSWER_TYPES = com.bridge.entity.tables.AnswerTypes.ANSWER_TYPES;

    /**
     * The table <code>public.survey_distributions</code>.
     */
    public final SurveyDistributions SURVEY_DISTRIBUTIONS = com.bridge.entity.tables.SurveyDistributions.SURVEY_DISTRIBUTIONS;

    /**
     * The table <code>public.survey_questions</code>.
     */
    public final SurveyQuestions SURVEY_QUESTIONS = com.bridge.entity.tables.SurveyQuestions.SURVEY_QUESTIONS;

    /**
     * The table <code>public.survey_templates</code>.
     */
    public final SurveyTemplates SURVEY_TEMPLATES = com.bridge.entity.tables.SurveyTemplates.SURVEY_TEMPLATES;

    /**
     * The table <code>public.surveys</code>.
     */
    public final Surveys SURVEYS = com.bridge.entity.tables.Surveys.SURVEYS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ANSWER_OPTIONS_ID_SEQ,
            Sequences.ANSWER_TYPES_ID_SEQ,
            Sequences.SURVEY_DISTRIBUTIONS_ID_SEQ,
            Sequences.SURVEY_QUESTIONS_ID_SEQ,
            Sequences.SURVEY_TEMPLATES_ID_SEQ,
            Sequences.SURVEYS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AnswerOptions.ANSWER_OPTIONS,
            AnswerTypes.ANSWER_TYPES,
            SurveyDistributions.SURVEY_DISTRIBUTIONS,
            SurveyQuestions.SURVEY_QUESTIONS,
            SurveyTemplates.SURVEY_TEMPLATES,
            Surveys.SURVEYS);
    }
}
