/**
 * This class is generated by jOOQ
 */
package com.bridge.entity;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.answer_options_id_seq</code>
     */
    public static final Sequence<Long> ANSWER_OPTIONS_ID_SEQ = new SequenceImpl<Long>("answer_options_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.answer_types_id_seq</code>
     */
    public static final Sequence<Long> ANSWER_TYPES_ID_SEQ = new SequenceImpl<Long>("answer_types_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.survey_distributions_id_seq</code>
     */
    public static final Sequence<Long> SURVEY_DISTRIBUTIONS_ID_SEQ = new SequenceImpl<Long>("survey_distributions_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.survey_questions_id_seq</code>
     */
    public static final Sequence<Long> SURVEY_QUESTIONS_ID_SEQ = new SequenceImpl<Long>("survey_questions_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.survey_templates_id_seq</code>
     */
    public static final Sequence<Long> SURVEY_TEMPLATES_ID_SEQ = new SequenceImpl<Long>("survey_templates_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.surveys_id_seq</code>
     */
    public static final Sequence<Long> SURVEYS_ID_SEQ = new SequenceImpl<Long>("surveys_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
