/**
 * This class is generated by jOOQ
 */
package com.bridge.entity;


import com.bridge.entity.tables.AnswerOptions;
import com.bridge.entity.tables.AnswerTypes;
import com.bridge.entity.tables.SurveyDistributions;
import com.bridge.entity.tables.SurveyQuestions;
import com.bridge.entity.tables.SurveyTemplates;
import com.bridge.entity.tables.Surveys;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.answer_options</code>.
     */
    public static final AnswerOptions ANSWER_OPTIONS = com.bridge.entity.tables.AnswerOptions.ANSWER_OPTIONS;

    /**
     * The table <code>public.answer_types</code>.
     */
    public static final AnswerTypes ANSWER_TYPES = com.bridge.entity.tables.AnswerTypes.ANSWER_TYPES;

    /**
     * The table <code>public.survey_distributions</code>.
     */
    public static final SurveyDistributions SURVEY_DISTRIBUTIONS = com.bridge.entity.tables.SurveyDistributions.SURVEY_DISTRIBUTIONS;

    /**
     * The table <code>public.survey_questions</code>.
     */
    public static final SurveyQuestions SURVEY_QUESTIONS = com.bridge.entity.tables.SurveyQuestions.SURVEY_QUESTIONS;

    /**
     * The table <code>public.survey_templates</code>.
     */
    public static final SurveyTemplates SURVEY_TEMPLATES = com.bridge.entity.tables.SurveyTemplates.SURVEY_TEMPLATES;

    /**
     * The table <code>public.surveys</code>.
     */
    public static final Surveys SURVEYS = com.bridge.entity.tables.Surveys.SURVEYS;
}
