/**
 * This class is generated by jOOQ
 */
package com.bridge.survey.entity;


import com.bridge.survey.entity.tables.SurveyDistribution;
import com.bridge.survey.entity.tables.Surveys;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1836696602;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.survey_distribution</code>.
     */
    public final SurveyDistribution SURVEY_DISTRIBUTION = SurveyDistribution.SURVEY_DISTRIBUTION;

    /**
     * The table <code>public.surveys</code>.
     */
    public final Surveys SURVEYS = Surveys.SURVEYS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SurveyDistribution.SURVEY_DISTRIBUTION,
            Surveys.SURVEYS);
    }
}
