/**
 * This class is generated by jOOQ
 */
package com.bridge.survey.entity;


import com.bridge.survey.entity.tables.SurveyDistribution;
import com.bridge.survey.entity.tables.Surveys;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.survey_distribution</code>.
     */
    public static final SurveyDistribution SURVEY_DISTRIBUTION = SurveyDistribution.SURVEY_DISTRIBUTION;

    /**
     * The table <code>public.surveys</code>.
     */
    public static final Surveys SURVEYS = Surveys.SURVEYS;
}
