/**
 * This class is generated by jOOQ
 */
package com.bridge.entity.tables.records;


import com.bridge.entity.tables.SurveyQuestions;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SurveyQuestionsRecord extends UpdatableRecordImpl<SurveyQuestionsRecord> implements Record12<Long, String, Long, Boolean, Long, Long, String, String, String, Timestamp, Timestamp, Boolean> {

    private static final long serialVersionUID = -126920060;

    /**
     * Setter for <code>public.survey_questions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.survey_questions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.survey_questions.question_text</code>.
     */
    public void setQuestionText(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.survey_questions.question_text</code>.
     */
    public String getQuestionText() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.survey_questions.survey_id</code>.
     */
    public void setSurveyId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.survey_questions.survey_id</code>.
     */
    public Long getSurveyId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.survey_questions.is_required</code>.
     */
    public void setIsRequired(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.survey_questions.is_required</code>.
     */
    public Boolean getIsRequired() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.survey_questions.answer_type_id</code>.
     */
    public void setAnswerTypeId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.survey_questions.answer_type_id</code>.
     */
    public Long getAnswerTypeId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.survey_questions.option_id</code>.
     */
    public void setOptionId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.survey_questions.option_id</code>.
     */
    public Long getOptionId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.survey_questions.pre_text_message</code>.
     */
    public void setPreTextMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.survey_questions.pre_text_message</code>.
     */
    public String getPreTextMessage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.survey_questions.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.survey_questions.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.survey_questions.updated_by</code>.
     */
    public void setUpdatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.survey_questions.updated_by</code>.
     */
    public String getUpdatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.survey_questions.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.survey_questions.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>public.survey_questions.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.survey_questions.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>public.survey_questions.is_allow_pre_text</code>.
     */
    public void setIsAllowPreText(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.survey_questions.is_allow_pre_text</code>.
     */
    public Boolean getIsAllowPreText() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, Long, Boolean, Long, Long, String, String, String, Timestamp, Timestamp, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, String, Long, Boolean, Long, Long, String, String, String, Timestamp, Timestamp, Boolean> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SurveyQuestions.SURVEY_QUESTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SurveyQuestions.SURVEY_QUESTIONS.QUESTION_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return SurveyQuestions.SURVEY_QUESTIONS.SURVEY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return SurveyQuestions.SURVEY_QUESTIONS.IS_REQUIRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return SurveyQuestions.SURVEY_QUESTIONS.ANSWER_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return SurveyQuestions.SURVEY_QUESTIONS.OPTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SurveyQuestions.SURVEY_QUESTIONS.PRE_TEXT_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return SurveyQuestions.SURVEY_QUESTIONS.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return SurveyQuestions.SURVEY_QUESTIONS.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return SurveyQuestions.SURVEY_QUESTIONS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return SurveyQuestions.SURVEY_QUESTIONS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return SurveyQuestions.SURVEY_QUESTIONS.IS_ALLOW_PRE_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getQuestionText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSurveyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsRequired();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getAnswerTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getOptionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPreTextMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getIsAllowPreText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value2(String value) {
        setQuestionText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value3(Long value) {
        setSurveyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value4(Boolean value) {
        setIsRequired(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value5(Long value) {
        setAnswerTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value6(Long value) {
        setOptionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value7(String value) {
        setPreTextMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value8(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value9(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value10(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value11(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord value12(Boolean value) {
        setIsAllowPreText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyQuestionsRecord values(Long value1, String value2, Long value3, Boolean value4, Long value5, Long value6, String value7, String value8, String value9, Timestamp value10, Timestamp value11, Boolean value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SurveyQuestionsRecord
     */
    public SurveyQuestionsRecord() {
        super(SurveyQuestions.SURVEY_QUESTIONS);
    }

    /**
     * Create a detached, initialised SurveyQuestionsRecord
     */
    public SurveyQuestionsRecord(Long id, String questionText, Long surveyId, Boolean isRequired, Long answerTypeId, Long optionId, String preTextMessage, String createdBy, String updatedBy, Timestamp createdAt, Timestamp updatedAt, Boolean isAllowPreText) {
        super(SurveyQuestions.SURVEY_QUESTIONS);

        set(0, id);
        set(1, questionText);
        set(2, surveyId);
        set(3, isRequired);
        set(4, answerTypeId);
        set(5, optionId);
        set(6, preTextMessage);
        set(7, createdBy);
        set(8, updatedBy);
        set(9, createdAt);
        set(10, updatedAt);
        set(11, isAllowPreText);
    }
}
