/**
 * This class is generated by jOOQ
 */
package com.bridge.entity.tables;


import com.bridge.entity.Keys;
import com.bridge.entity.Public;
import com.bridge.entity.tables.records.AnswerTypesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnswerTypes extends TableImpl<AnswerTypesRecord> {

    private static final long serialVersionUID = 1253071690;

    /**
     * The reference instance of <code>public.answer_types</code>
     */
    public static final AnswerTypes ANSWER_TYPES = new AnswerTypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AnswerTypesRecord> getRecordType() {
        return AnswerTypesRecord.class;
    }

    /**
     * The column <code>public.answer_types.id</code>.
     */
    public final TableField<AnswerTypesRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.answer_types.answer_type</code>.
     */
    public final TableField<AnswerTypesRecord, String> ANSWER_TYPE = createField("answer_type", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.answer_types.created_at</code>.
     */
    public final TableField<AnswerTypesRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.answer_types.updated_at</code>.
     */
    public final TableField<AnswerTypesRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.answer_types.created_by</code>.
     */
    public final TableField<AnswerTypesRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.answer_types.updated_by</code>.
     */
    public final TableField<AnswerTypesRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.answer_types</code> table reference
     */
    public AnswerTypes() {
        this("answer_types", null);
    }

    /**
     * Create an aliased <code>public.answer_types</code> table reference
     */
    public AnswerTypes(String alias) {
        this(alias, ANSWER_TYPES);
    }

    private AnswerTypes(String alias, Table<AnswerTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private AnswerTypes(String alias, Table<AnswerTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AnswerTypesRecord> getPrimaryKey() {
        return Keys.ANSWER_TYPE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AnswerTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<AnswerTypesRecord>>asList(Keys.ANSWER_TYPE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnswerTypes as(String alias) {
        return new AnswerTypes(alias, this);
    }

    /**
     * Rename this table
     */
    public AnswerTypes rename(String name) {
        return new AnswerTypes(name, null);
    }
}
