/**
 * This class is generated by jOOQ
 */
package com.bridge.entity.tables;


import com.bridge.entity.Keys;
import com.bridge.entity.Public;
import com.bridge.entity.tables.records.SurveyDistributionsRecord;

import java.sql.Time;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SurveyDistributions extends TableImpl<SurveyDistributionsRecord> {

    private static final long serialVersionUID = -1413919831;

    /**
     * The reference instance of <code>public.survey_distributions</code>
     */
    public static final SurveyDistributions SURVEY_DISTRIBUTIONS = new SurveyDistributions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SurveyDistributionsRecord> getRecordType() {
        return SurveyDistributionsRecord.class;
    }

    /**
     * The column <code>public.survey_distributions.id</code>.
     */
    public final TableField<SurveyDistributionsRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.survey_distributions.survey_id</code>.
     */
    public final TableField<SurveyDistributionsRecord, Long> SURVEY_ID = createField("survey_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.survey_distributions.name</code>.
     */
    public final TableField<SurveyDistributionsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.survey_distributions.closes_at</code>.
     */
    public final TableField<SurveyDistributionsRecord, Time> CLOSES_AT = createField("closes_at", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

    /**
     * The column <code>public.survey_distributions.created_at</code>.
     */
    public final TableField<SurveyDistributionsRecord, Time> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>public.survey_distributions.updated_at</code>.
     */
    public final TableField<SurveyDistributionsRecord, Time> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>public.survey_distributions.created_by</code>.
     */
    public final TableField<SurveyDistributionsRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.survey_distributions.updated_by</code>.
     */
    public final TableField<SurveyDistributionsRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.survey_distributions</code> table reference
     */
    public SurveyDistributions() {
        this("survey_distributions", null);
    }

    /**
     * Create an aliased <code>public.survey_distributions</code> table reference
     */
    public SurveyDistributions(String alias) {
        this(alias, SURVEY_DISTRIBUTIONS);
    }

    private SurveyDistributions(String alias, Table<SurveyDistributionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SurveyDistributions(String alias, Table<SurveyDistributionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SurveyDistributionsRecord> getPrimaryKey() {
        return Keys.SURVEY_DISTRIBUTION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SurveyDistributionsRecord>> getKeys() {
        return Arrays.<UniqueKey<SurveyDistributionsRecord>>asList(Keys.SURVEY_DISTRIBUTION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SurveyDistributionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SurveyDistributionsRecord, ?>>asList(Keys.SURVEY_DISTRIBUTIONS__SURVEY_DISTRIBUTION_SURVEY_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyDistributions as(String alias) {
        return new SurveyDistributions(alias, this);
    }

    /**
     * Rename this table
     */
    public SurveyDistributions rename(String name) {
        return new SurveyDistributions(name, null);
    }
}
