/**
 * This class is generated by jOOQ
 */
package com.bridge.entity.tables;


import com.bridge.entity.Keys;
import com.bridge.entity.Public;
import com.bridge.entity.tables.records.SurveysRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Surveys extends TableImpl<SurveysRecord> {

    private static final long serialVersionUID = 1095500762;

    /**
     * The reference instance of <code>public.surveys</code>
     */
    public static final Surveys SURVEYS = new Surveys();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SurveysRecord> getRecordType() {
        return SurveysRecord.class;
    }

    /**
     * The column <code>public.surveys.id</code>.
     */
    public final TableField<SurveysRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.surveys.name</code>.
     */
    public final TableField<SurveysRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.surveys.created_at</code>.
     */
    public final TableField<SurveysRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.surveys.updated_at</code>.
     */
    public final TableField<SurveysRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.surveys.created_by</code>.
     */
    public final TableField<SurveysRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.surveys.updated_by</code>.
     */
    public final TableField<SurveysRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.surveys</code> table reference
     */
    public Surveys() {
        this("surveys", null);
    }

    /**
     * Create an aliased <code>public.surveys</code> table reference
     */
    public Surveys(String alias) {
        this(alias, SURVEYS);
    }

    private Surveys(String alias, Table<SurveysRecord> aliased) {
        this(alias, aliased, null);
    }

    private Surveys(String alias, Table<SurveysRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SurveysRecord> getPrimaryKey() {
        return Keys.SURVEYS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SurveysRecord>> getKeys() {
        return Arrays.<UniqueKey<SurveysRecord>>asList(Keys.SURVEYS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Surveys as(String alias) {
        return new Surveys(alias, this);
    }

    /**
     * Rename this table
     */
    public Surveys rename(String name) {
        return new Surveys(name, null);
    }
}
