/**
 * This class is generated by jOOQ
 */
package com.bridge.entity.tables;


import com.bridge.entity.Keys;
import com.bridge.entity.Public;
import com.bridge.entity.tables.records.SurveyTemplatesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SurveyTemplates extends TableImpl<SurveyTemplatesRecord> {

    private static final long serialVersionUID = -437372231;

    /**
     * The reference instance of <code>public.survey_templates</code>
     */
    public static final SurveyTemplates SURVEY_TEMPLATES = new SurveyTemplates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SurveyTemplatesRecord> getRecordType() {
        return SurveyTemplatesRecord.class;
    }

    /**
     * The column <code>public.survey_templates.id</code>.
     */
    public final TableField<SurveyTemplatesRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.survey_templates.json_data</code>.
     */
    public final TableField<SurveyTemplatesRecord, Object> JSON_DATA = createField("json_data", org.jooq.impl.SQLDataType.OTHER.nullable(false), this, "");

    /**
     * The column <code>public.survey_templates.name</code>.
     */
    public final TableField<SurveyTemplatesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.survey_templates.created_by</code>.
     */
    public final TableField<SurveyTemplatesRecord, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.survey_templates.updated_by</code>.
     */
    public final TableField<SurveyTemplatesRecord, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.survey_templates.created_at</code>.
     */
    public final TableField<SurveyTemplatesRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.survey_templates.updated_at</code>.
     */
    public final TableField<SurveyTemplatesRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.survey_templates</code> table reference
     */
    public SurveyTemplates() {
        this("survey_templates", null);
    }

    /**
     * Create an aliased <code>public.survey_templates</code> table reference
     */
    public SurveyTemplates(String alias) {
        this(alias, SURVEY_TEMPLATES);
    }

    private SurveyTemplates(String alias, Table<SurveyTemplatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private SurveyTemplates(String alias, Table<SurveyTemplatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SurveyTemplatesRecord> getPrimaryKey() {
        return Keys.SURVEY_TEMPLATE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SurveyTemplatesRecord>> getKeys() {
        return Arrays.<UniqueKey<SurveyTemplatesRecord>>asList(Keys.SURVEY_TEMPLATE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyTemplates as(String alias) {
        return new SurveyTemplates(alias, this);
    }

    /**
     * Rename this table
     */
    public SurveyTemplates rename(String name) {
        return new SurveyTemplates(name, null);
    }
}
